swagger: '2.0'

# basic meta information
info:
  title: nakadi-mock-clj
  version: '1.0'
  description: Very nice nakadi-mock-clj

externalDocs:
  description: External docs
  url: http://example.github.io/

# technical configuration
basePath: /
produces:
- application/json
consumes:
- application/json

paths:

  '/':
    get:
      summary: Application root
      operationId: org.zalando.stups.friboo.system.http/redirect-to-swagger-ui
      responses:
        default:
          description: "Redirects to /ui/"

  '/hello/{name}':
    get:
      summary: Says hello
      description: |
        Says hello personally to {name}
      parameters:
        - $ref: '#/parameters/Name'
      tags:
        - General
      operationId: "nakadi-mock-clj.api/get-hello"
      responses:
        200:
          description: Hello is said
        default:
          $ref: '#/responses/Error'

parameters:
  Name:
    name: name
    in: path
    type: string
    description: Name of the person to greet

responses:
  Error:
    description: An error occured.
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    example:
      message: Internal Server Error
