swagger: '2.0'

# basic meta information
info:
  title: nakadi-mock-clj
  version: '1.0'
  description: Very nice nakadi-mock-clj

externalDocs:
  description: External docs
  url: https://github.bus.zalan.do/jyun/nakadi-mock-clj

# technical configuration
basePath: /
produces:
- application/json
consumes:
- application/json

paths:

  '/':
    get:
      summary: Application root
      operationId: org.zalando.stups.friboo.system.http/redirect-to-swagger-ui
      responses:
        default:
          description: "Redirects to /ui/"

  '/subscriptions':
    get:
      summary: Get every subscriptions
      description: |
        Returns every subscriptions stored in mock server
      tags:
        - Subscription
      operationId: "nakadi-mock-clj.api/list-subscription"
      responses:
        200:
          description: Ok
        default:
          $ref: '#/responses/Error'
    post:
      summary: Save new subscription
      description: |
        Saves new subscription which passed as request body
      tags:
        - Subscription
      operationId: "nakadi-mock-clj.api/save-subscription"
      responses:
        201:
          description: Saved New
        200:
          description: Already have identical one, not updated
        400:
          description: Request with unknown fields
        422:
          description: Request without required fields
        default:
          $ref: '#/responses/Error'

responses:
  Error:
    description: An error occured.
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    example:
      message: Internal Server Error
